name: ✨ Feature Request
description: Suggest a new feature or enhancement for piper-templates
title: "feat: "
labels: ["feat"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below to help us understand your request.

  - type: input
    id: template-area
    attributes:
      label: Which template would this feature affect?
      description: Enter the template path (e.g., ts/with-turborepo, ai/with-awesome-copilot) or "new template" for proposals
      placeholder: "ts/with-turborepo"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Describe the feature you'd like to see
      placeholder: What would you like to add or change?
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, examples, or screenshots
      placeholder: Links to similar features, code examples, mockups, etc.
    validations:
      required: false
